apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  APP_HOST: {{ .Values.config.appHost | quote }}
  APP_PORT: {{ .Values.config.appPort | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  JWT_ALGORITHM: {{ .Values.config.jwtAlgorithm | quote }}
  JWT_EXPIRATION_MINUTES: {{ .Values.config.jwtExpirationMinutes | quote }}
  POSTGRESQL_HOST: {{ .Values.database.host | quote }}
  POSTGRESQL_PORT: {{ .Values.database.port | quote }}
  POSTGRESQL_DB_NAME: {{ .Values.database.name | quote }}
  POSTGRESQL_USER: {{ .Values.database.user | quote }}
